In [1]:
import pandas as pd

Read Salaries.csv as a dataframe called sal.

In [2]:
sal=pd.read_csv('Salaries.csv')

Check the head of the DataFrame.

In [4]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco

In [5]:
sal.info()

<class 'pandas.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                79 non-null     int64
 1   EmployeeName      79 non-null     str
 2   JobTitle          79 non-null     str
 3   BasePay           79 non-null     float64
 4   OvertimePay       79 non-null     float64
 5   OtherPay          79 non-null     float64
 6   Benefits          0 non-null      float64
 7   TotalPay          79 non-null     float64
 8   TotalPayBenefits  79 non-null     float64
 9   Year              79 non-null     int64
 10  Notes             0 non-null      float64
 11  Agency            79 non-null     str
dtypes: float64(7), int64(2), str(3)
memory usage: 7.5 KB

What is the average BasePay ?

In [8]:
sal['BasePay'].mean()

np.float64(176365.55113924053)

what is the highest amount of OvertimePay in the dataset ?

In [9]:
sal['OvertimePay'].max()

np.float64(245131.88)

What is the job title of JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get
an answer that doesn't match up (there is also a lowercase Joseph Driscoll).

In [12]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

How much does JOSEPH DRISCOLL make (including benefits)?

In [14]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

What is the name of highest paid person (including benefits)?

In [13]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].max()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco

What is the name of lowest paid person (including benefits)? Do you notice something
strange about how much he or she is paid?

In [18]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency
78,79,MICHAEL DELANE,"CAPTAIN, FIRE SUPPRESSION",140546.88,62283.7,28821.55,NaN,231652.13,231652.13,2011,NaN,San Francisco

What was the average (mean) BasePay of all employees per year? (2011-2014) ?

In [21]:
sal.shape

(79, 12)

In [22]:
sal=pd.read_csv('Salaries.csv')

In [24]:
sal.shape

(79, 12)

In [23]:
sal['Year'].unique()

array([2011])

What was the average (mean) BasePay of all employees per year?

In [25]:
sal.groupby('Year')['BasePay'].mean()

Year
2011    176365.551139
Name: BasePay, dtype: float64

How many unique job titles are there?

In [30]:
sal['JobTitle'].nunique()

31

What are the top 5 most common jobs?